### ISSUE TITLE
SchemaEvaluator: alignment file missing raising error

### ISSUE THREAD

**Issue by domenico-simone** [B-UMMI/chewBBACA#119]
Hello,

while using the SchemaEvaluator module, I got the following error:

```bash
Traceback (most recent call last):
  File "/lustrehome/dsimone/miniconda3/envs/chewbbaca/bin/chewBBACA.py", line 8, in <module>
    sys.exit(main())
  File "/lustrehome/dsimone/miniconda3/envs/chewbbaca/lib/python3.6/site-packages/CHEWBBACA/chewBBACA.py", line 1414, in main
    functions_info[process][1]()
  File "/lustrehome/dsimone/miniconda3/envs/chewbbaca/lib/python3.6/site-packages/CHEWBBACA/utils/process_datetime.py", line 149, in wrapper
    func(*args, **kwargs)
  File "/lustrehome/dsimone/miniconda3/envs/chewbbaca/lib/python3.6/site-packages/CHEWBBACA/chewBBACA.py", line 597, in evaluate_schema
    input_files, pre_computed_data_path, protein_file_path, output_file, minimum_length, chewie_schema=True)
  File "/lustrehome/dsimone/miniconda3/envs/chewbbaca/lib/python3.6/site-packages/CHEWBBACA/SchemaEvaluator/schema_evaluator.py", line 1269, in write_individual_html
    msa_seq_gen = SeqIO.parse(msa_file_path, "fasta")
  File "/lustrehome/dsimone/miniconda3/envs/chewbbaca/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 607, in parse
    return iterator_generator(handle)
  File "/lustrehome/dsimone/miniconda3/envs/chewbbaca/lib/python3.6/site-packages/Bio/SeqIO/FastaIO.py", line 183, in __init__
    super().__init__(source, mode="t", fmt="Fasta")
  File "/lustrehome/dsimone/miniconda3/envs/chewbbaca/lib/python3.6/site-packages/Bio/SeqIO/Interfaces.py", line 47, in __init__
    self.stream = open(source, "r" + mode)
FileNotFoundError: [Errno 2] No such file or directory: 'SchemaEvaluator/SchemaEvaluator_pre_computed_data/prot_files/genome1-protein1171_aligned.fasta'
```

I checked the file `genome1-protein1171.fasta` and turns out it has only one sequence, therefore my hypothesis is that the alignment file was not generated. Is there any way I can overcome this issue?

Thank you

Domenico

**Comment by ramirma** [comment]
Following up on @rfm-targa's response you can use our general email imm-bioinfo[at]medicina.ulisboa.pt if you would like to send it privately.

**Comment by rfm-targa** [comment]
Closing this issue due to inactivity. We have made many changes to chewBBACA to fix several bugs. Please update to the latest version if you still have issues with the SchemaEvaluator module.
