### ISSUE TITLE
unable to run tutorail with chewBBACA-2.8.5

### ISSUE THREAD

**Issue by EricDeveaud** [B-UMMI/chewBBACA#120]
Hello While trying a fresh install of chewBBACA-2.8.5 installed from:
https://files.pythonhosted.org/packages/6c/2c/4d895628a2cc1f2fc0e07cef9d5c0d703c17b8aaea2ab21e835961ff00c4/chewBBACA-2.8.5.tar.gz

I have the following error while trying to run the tutorial: https://github.com/B-UMMI/chewBBACA_tutorial
see:
```
rpm_maker:2.7.0/chewBBACA_tutorial > chewBBACA.py CreateSchema -i complete_genomes/ -o tutorial_schema --ptf Streptococcus_agalactiae.trn --cpu 6

chewBBACA version: 2.8.5
Authors: Mickael Silva, Pedro Cerqueira, Rafael Mamede
Github: https://github.com/B-UMMI/chewBBACA
Wiki: https://github.com/B-UMMI/chewBBACA/wiki
Tutorial: https://github.com/B-UMMI/chewBBACA_tutorial
Contacts: imm-bioinfo@medicina.ulisboa.pt

============================
  chewBBACA - CreateSchema
============================
Started at: 2022-03-08T11:41:34

Prodigal training file: Streptococcus_agalactiae.trn
CPU cores: 6
BLAST Score Ratio: 0.6
Translation table: 11
Minimum sequence length: 201
Size threshold: 0.2
Word size: 5
Window size: 5
Clustering similarity: 0.2
Representative filter: 0.9
Intra-cluster filter: 0.9
Number of inputs: 32

Predicting gene sequences...

 [====================] 100%

Extracting coding sequences...

 [====================] 100%

Extracted a total of 64217 coding sequences from 32 genomes.

Removing duplicated sequences...removed 1143394 sequences.

Removing sequences smaller than 201 nucleotides...removed 5950 sequences.

Translating 19922 DNA sequences...

Error on translate_coding_sequences:
Traceback (most recent call last):
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/chewBBACA-2.8.5-py3.8.egg/CHEWBBACA/utils/multiprocessing_operations.py", line 39, in function_helper
    results = input_args[-1](*input_args[0:-1])
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/chewBBACA-2.8.5-py3.8.egg/CHEWBBACA/utils/sequence_manipulation.py", line 526, in translate_coding_sequences
    cds_index = SeqIO.index(sequences_file, 'fasta')
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/biopython-1.79-py3.8-linux-x86_64.egg/Bio/SeqIO/__init__.py", line 875, in index
    return _IndexedSeqFileDict(
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/biopython-1.79-py3.8-linux-x86_64.egg/Bio/File.py", line 199, in __init__
    raise ValueError("Duplicate key '%s'" % key)
ValueError: Duplicate key 'GCA_000007265-protein1'


Error on translate_coding_sequences:
Traceback (most recent call last):
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/chewBBACA-2.8.5-py3.8.egg/CHEWBBACA/utils/multiprocessing_operations.py", line 39, in function_helper
    results = input_args[-1](*input_args[0:-1])
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/chewBBACA-2.8.5-py3.8.egg/CHEWBBACA/utils/sequence_manipulation.py", line 526, in translate_coding_sequences
    cds_index = SeqIO.index(sequences_file, 'fasta')
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/biopython-1.79-py3.8-linux-x86_64.egg/Bio/SeqIO/__init__.py", line 875, in index
    return _IndexedSeqFileDict(
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/biopython-1.79-py3.8-linux-x86_64.egg/Bio/File.py", line 199, in __init__
    raise ValueError("Duplicate key '%s'" % key)
ValueError: Duplicate key 'GCA_000007265-protein1'


Error on translate_coding_sequences:
Traceback (most recent call last):
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/chewBBACA-2.8.5-py3.8.egg/CHEWBBACA/utils/multiprocessing_operations.py", line 39, in function_helper
    results = input_args[-1](*input_args[0:-1])
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/chewBBACA-2.8.5-py3.8.egg/CHEWBBACA/utils/sequence_manipulation.py", line 526, in translate_coding_sequences
    cds_index = SeqIO.index(sequences_file, 'fasta')
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/biopython-1.79-py3.8-linux-x86_64.egg/Bio/SeqIO/__init__.py", line 875, in index
    return _IndexedSeqFileDict(
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/biopython-1.79-py3.8-linux-x86_64.egg/Bio/File.py", line 199, in __init__
    raise ValueError("Duplicate key '%s'" % key)
ValueError: Duplicate key 'GCA_000007265-protein1'



Error on translate_coding_sequences:
Traceback (most recent call last):
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/chewBBACA-2.8.5-py3.8.egg/CHEWBBACA/utils/multiprocessing_operations.py", line 39, in function_helper
    results = input_args[-1](*input_args[0:-1])
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/chewBBACA-2.8.5-py3.8.egg/CHEWBBACA/utils/sequence_manipulation.py", line 526, in translate_coding_sequences
    cds_index = SeqIO.index(sequences_file, 'fasta')
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/biopython-1.79-py3.8-linux-x86_64.egg/Bio/SeqIO/__init__.py", line 875, in index
    return _IndexedSeqFileDict(
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/biopython-1.79-py3.8-linux-x86_64.egg/Bio/File.py", line 199, in __init__
    raise ValueError("Duplicate key '%s'" % key)
ValueError: Duplicate key 'GCA_000007265-protein1'





Error on translate_coding_sequences:
Traceback (most recent call last):
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/chewBBACA-2.8.5-py3.8.egg/CHEWBBACA/utils/multiprocessing_operations.py", line 39, in function_helper
    results = input_args[-1](*input_args[0:-1])
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/chewBBACA-2.8.5-py3.8.egg/CHEWBBACA/utils/sequence_manipulation.py", line 526, in translate_coding_sequences
    cds_index = SeqIO.index(sequences_file, 'fasta')
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/biopython-1.79-py3.8-linux-x86_64.egg/Bio/SeqIO/__init__.py", line 875, in index
    return _IndexedSeqFileDict(
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/biopython-1.79-py3.8-linux-x86_64.egg/Bio/File.py", line 199, in __init__
    raise ValueError("Duplicate key '%s'" % key)
ValueError: Duplicate key 'GCA_000007265-protein1'



Error on translate_coding_sequences:
Traceback (most recent call last):
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/chewBBACA-2.8.5-py3.8.egg/CHEWBBACA/utils/multiprocessing_operations.py", line 39, in function_helper
    results = input_args[-1](*input_args[0:-1])
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/chewBBACA-2.8.5-py3.8.egg/CHEWBBACA/utils/sequence_manipulation.py", line 526, in translate_coding_sequences
    cds_index = SeqIO.index(sequences_file, 'fasta')
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/biopython-1.79-py3.8-linux-x86_64.egg/Bio/SeqIO/__init__.py", line 875, in index
    return _IndexedSeqFileDict(
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/biopython-1.79-py3.8-linux-x86_64.egg/Bio/File.py", line 199, in __init__
    raise ValueError("Duplicate key '%s'" % key)
ValueError: Duplicate key 'GCA_000007265-protein1'


Traceback (most recent call last):
  File "/opt/gensoft/exe/chewBBACA/2.8.5/bin/chewBBACA.py", line 11, in <module>
    load_entry_point('chewBBACA==2.8.5', 'console_scripts', 'chewBBACA.py')()
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/chewBBACA-2.8.5-py3.8.egg/CHEWBBACA/chewBBACA.py", line 1480, in main
    functions_info[process][1]()
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/chewBBACA-2.8.5-py3.8.egg/CHEWBBACA/utils/process_datetime.py", line 149, in wrapper
    func(*args, **kwargs)
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/chewBBACA-2.8.5-py3.8.egg/CHEWBBACA/chewBBACA.py", line 193, in create_schema
    CreateSchema.main(**vars(args))
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/chewBBACA-2.8.5-py3.8.egg/CHEWBBACA/createschema/CreateSchema.py", line 1192, in main
    results = create_schema_seed(input_files, output_directory, schema_name,
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/chewBBACA-2.8.5-py3.8.egg/CHEWBBACA/createschema/CreateSchema.py", line 991, in create_schema_seed
    ts_results = translate_sequences(schema_seqids, distinct_seqs_file,
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/chewBBACA-2.8.5-py3.8.egg/CHEWBBACA/createschema/CreateSchema.py", line 498, in translate_sequences
    untrans_lines.extend(['{0}: {1}'.format(r[0], r[1])
  File "/opt/gensoft/exe/chewBBACA/2.8.5/venv/lib/python3.8/site-packages/chewBBACA-2.8.5-py3.8.egg/CHEWBBACA/createschema/CreateSchema.py", line 498, in <listcomp>
    untrans_lines.extend(['{0}: {1}'.format(r[0], r[1])
IndexError: string index out of range
rpm_maker:2.7.0/chewBBACA_tutorial > 
```

nb using following external tools :
```
prodigal/2.6.3
blast+/2.10.0
fasta/3.8h
mafft/7.467
```

regards

Eric

**Comment by EricDeveaud** [comment]
used python modules:
```
biopython==1.79
certifi==2021.10.8
charset-normalizer==2.0.12
chewBBACA==2.8.5
idna==3.3
isodate==0.6.1
numpy==1.22.3
pandas==1.4.1
plotly==5.6.0
pyparsing==3.0.7
python-dateutil==2.8.2
pytz==2021.3
rdflib==6.1.1
requests==2.27.1
scipy==1.8.0
six==1.16.0
SPARQLWrapper==1.8.5
tenacity==8.0.1
urllib3==1.26.8
```

**Comment by rfm-targa** [comment]
Hello @EricDeveaud,

That error about duplicated sequence identifiers might be raised if the path you passed to the `-o` parameter exists and has files from a previous run. The text printed to the stdout also reports that 64,217 coding sequences (CDSs) were extracted from the input genomes, but in a sequence deduplication step it reports that it found 1,143,394 duplicated sequences. Detecting a number of duplicated sequences that exceeds the number of CDSs extracted from the input genomes also points to a problem related with files from a previous run that are in the same directories the current run is writing to.
Let us know if this was the case.

Best regards,

Rafael

**Comment by EricDeveaud** [comment]
indeed. sorry for the noise

regards

Eric

**Comment by rfm-targa** [comment]
A future release will include a warning when it detects files from a previous run and a parameter to force delete those files. The current behavior is not very clear. Thank you for reporting this.

Best regards,

Rafael
