### ISSUE TITLE
AlleleCall error

### ISSUE THREAD

**Issue by ireneortega** [B-UMMI/chewBBACA#143]
I am running the following commands but I got an error in AlleleCall:

```
$ chewBBACA.py PrepExternalSchema -i /home/irene/PubMLST_cgMLST_120922 --ptf /home/irene/chewBBACA/CHEWBBACA/prodigal_training_files/Campylobacter_jejuni.trn -o /home/irene/cgmlst_paper4/1_chewbacca/schema --cpu 6

chewBBACA version: 2.8.5
Authors: Mickael Silva, Pedro Cerqueira, Rafael Mamede
Github: https://github.com/B-UMMI/chewBBACA
Wiki: https://github.com/B-UMMI/chewBBACA/wiki
Tutorial: https://github.com/B-UMMI/chewBBACA_tutorial
Contacts: imm-bioinfo@medicina.ulisboa.pt

==================================
  chewBBACA - PrepExternalSchema
==================================
Started at: 2022-09-20T18:06:24

Adapting schema in the following directory:
/home/irene/PubMLST_cgMLST_120922
Prodigal training file:
/home/irene/chewBBACA/CHEWBBACA/prodigal_training_files/Campylobacter_jejuni.trn
Number of cores: 6
BLAST Score Ratio: 0.6
Translation table: 11
Minimum accepted sequence length: 0
Size threshold: 0.2
Number of genes to adapt: 1343

Determining the total number of alleles and allele mean length per gene...

Adapting 1343 genes...

 [====================] 100%

Number of invalid genes: 0
Number of invalid alleles: 1746

Successfully adapted 1343/1343 genes present in the input schema.

Finished at: 2022-09-20T18:19:28
Took  13m 4s

$ chewBBACA.py AlleleCall -i /home/irene/cgmlst_paper4/genomes --ptf /home/irene/chewBBACA/CHEWBBACA/prodigal_training_files/Campylobacter_jejuni.trn -g /home/irene/cgmlst_paper4/1_chewbacca/schema/schema_seed -o /home/irene/cgmlst_paper4/1_chewbacca/results_wgMLST --cpu 6

chewBBACA version: 2.8.5
Authors: Mickael Silva, Pedro Cerqueira, Rafael Mamede
Github: https://github.com/B-UMMI/chewBBACA
Wiki: https://github.com/B-UMMI/chewBBACA/wiki
Tutorial: https://github.com/B-UMMI/chewBBACA_tutorial
Contacts: imm-bioinfo@medicina.ulisboa.pt

==========================
  chewBBACA - AlleleCall
==========================
Started at: 2022-09-20T18:50:46

Warning! You have provided a CPU core count value that is equal to or exceeds the number of CPU cores in your system!
Resetting to: 4
It seems that your schema was created with chewBBACA 2.1.0 or lower.
It is highly recommended that you run the PrepExternalSchema process to guarantee full compatibility with the new chewBBACA version.
If you wish to continue, the AlleleCall process will convert the schema to v2.8.5, but will not determine if schema structure respects configuration values.
Do you wish to proceed?
yes


BLAST score ratio value:
0.6
Translation table value:
11
Minimum length value:
201
Size threshold value:
0.2

Adding Prodigal training file to schema...
Created /home/irene/cgmlst_paper4/1_chewbacca/schema/schema_seed/Campylobacter_jejuni.trn

Creating file with schema configs...
Traceback (most recent call last):
  File "/home/irene/.local/bin/chewBBACA.py", line 8, in <module>
    sys.exit(main())
  File "/home/irene/.local/lib/python3.8/site-packages/CHEWBBACA/chewBBACA.py", line 1480, in main
    functions_info[process][1]()
  File "/home/irene/.local/lib/python3.8/site-packages/CHEWBBACA/utils/process_datetime.py", line 149, in wrapper
    func(*args, **kwargs)
  File "/home/irene/.local/lib/python3.8/site-packages/CHEWBBACA/chewBBACA.py", line 373, in allele_call
    upgraded = pv.upgrade_legacy_schema(args.ptf_path, args.schema_directory,
  File "/home/irene/.local/lib/python3.8/site-packages/CHEWBBACA/utils/parameters_validation.py", line 861, in upgrade_legacy_schema
    schema_config = write_schema_config(blast_score_ratio, ptf_hash,
  File "/home/irene/.local/lib/python3.8/site-packages/CHEWBBACA/utils/parameters_validation.py", line 1255, in write_schema_config
    fo.pickle_dumper(params, config_file)
  File "/home/irene/.local/lib/python3.8/site-packages/CHEWBBACA/utils/file_operations.py", line 210, in pickle_dumper
    with open(output_file, 'wb') as po:
NotADirectoryError: [Errno 20] Not a directory: '/home/irene/cgmlst_paper4/1_chewbacca/schema/schema_seed/.schema_config'

```

I tried to create my own Prodigal training file as proposed [here](https://github.com/B-UMMI/chewBBACA/issues/136) and use that file instead of the one provided my chewBACCA but I got the same error. What can I do?

**Comment by ireneortega** [comment]
Sorry it was my fault. I made a mistake in the AlleleCall command. The name of output folder that stored the schema files was not written correctly. It should be:
`(prodigal) irene@irene-VirtualBox:~/cgmlst_paper4/1_chewbacca$ chewBBACA.py AlleleCall -i /home/irene/cgmlst_paper4/genomes --ptf /home/irene/chewBBACA/CHEWBBACA/prodigal_training_files/Campylobacter_jejuni.trn -g /home/irene/cgmlst_paper4/1_chewbacca/schema -o /home/irene/cgmlst_paper4/1_chewbacca/results_wgMLST --cpu 6`

However, I got a new error:
```
chewBBACA version: 2.8.5
Authors: Mickael Silva, Pedro Cerqueira, Rafael Mamede
Github: https://github.com/B-UMMI/chewBBACA
Wiki: https://github.com/B-UMMI/chewBBACA/wiki
Tutorial: https://github.com/B-UMMI/chewBBACA_tutorial
Contacts: imm-bioinfo@medicina.ulisboa.pt

==========================
  chewBBACA - AlleleCall
==========================
Started at: 2022-09-21T09:14:31

Warning! You have provided a CPU core count value that is equal to or exceeds the number of CPU cores in your system!
Resetting to: 4
Checking if genome files exist...
Checking if gene files exist...

Starting Prodigal at: 09:14:35-21/09/2022
Training file: /home/irene/chewBBACA/CHEWBBACA/prodigal_training_files/Campylobacter_jejuni.trn
 [====================] 100%
Finishing Prodigal at: 09:15:54-21/09/2022

Checking if Prodigal created all the necessary files...
378
Missing some files from prodigal. 1 missing files out of 145
Traceback (most recent call last):
  File "/home/irene/.local/lib/python3.8/site-packages/CHEWBBACA/allelecall/BBACA.py", line 378, in main
    raise ValueError(message)
ValueError: Missing some files from prodigal. 1 missing files out of 145

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/irene/.local/bin/chewBBACA.py", line 8, in <module>
    sys.exit(main())
  File "/home/irene/.local/lib/python3.8/site-packages/CHEWBBACA/chewBBACA.py", line 1480, in main
    functions_info[process][1]()
  File "/home/irene/.local/lib/python3.8/site-packages/CHEWBBACA/utils/process_datetime.py", line 149, in wrapper
    func(*args, **kwargs)
  File "/home/irene/.local/lib/python3.8/site-packages/CHEWBBACA/chewBBACA.py", line 409, in allele_call
    BBACA.main(genomes_files, schema_genes, args.cpu_cores,
  File "/home/irene/.local/lib/python3.8/site-packages/CHEWBBACA/allelecall/BBACA.py", line 418, in main
    raise ValueError(e)
ValueError: Missing some files from prodigal. 1 missing files out of 145
```
What can I do?

**Comment by ramirma** [comment]
Thank you for your interest in chewBBACA @ireneortega. Two comments regarding the errors you report:

1. Please use the same training file for allele calling, changing training file may result in inconsistent allele calls
2. The error you report seems to originate in prodigal. Did you check the consistency and integrity of the fasta files where you are performing allele call? This may result from an error in one of the files.

**Comment by ireneortega** [comment]
Ok, two of my input genome names shared the prefix before the first "." as reported earlier [here ](https://github.com/B-UMMI/chewBBACA/issues/108). I changed the first "." to "_" and the AlleleCall command seems to work.
