### ISSUE TITLE
Adapting external schema for Salmonella enterica from cgmlst.org

### ISSUE THREAD

**Issue by omegatro** [B-UMMI/chewBBACA#175]
Hello! Encountered an issue similar to #154 while adapting ridom [S.enterica schema](https://www.cgmlst.org/ncs/schema/4792159/locus/).

Assembly test file used in AlleleCall step is attached:
[2212071223_S91_contigs.fasta.zip](https://github.com/B-UMMI/chewBBACA/files/11439550/2212071223_S91_contigs.fasta.zip)
chewBBACA version: 3.1.2

After downloading and extracting allelic sequences the PrepExternalSchema was performed with no errors (2999/3001 genes adapted): `chewBBACA.py PrepExternalSchema --cpu 12 -i Salmonella_enterica -o Salmonella_enterica`

An attemt to perform AlleleCall:
`chewBBACA.py AlleleCall --cpu 12 -i ~/2212071223_S91_cbc_input/ -g Salmonella_enterica -o ~/2212071223_S91_cbc_test/`
has failed with the following error:

```
Traceback (most recent call last):
  File "/opt/conda/envs/chewbacca_cgmlst/bin/chewBBACA.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/envs/chewbacca_cgmlst/lib/python3.11/site-packages/CHEWBBACA/chewBBACA.py", line 1584, in main
    functions_info[process][1]()
  File "/opt/conda/envs/chewbacca_cgmlst/lib/python3.11/site-packages/CHEWBBACA/utils/process_datetime.py", line 146, in wrapper
    func(*args, **kwargs)
  File "/opt/conda/envs/chewbacca_cgmlst/lib/python3.11/site-packages/CHEWBBACA/chewBBACA.py", line 514, in allele_call
    AlleleCall.main(genome_list, loci_list, args.schema_directory,
  File "/opt/conda/envs/chewbacca_cgmlst/lib/python3.11/site-packages/CHEWBBACA/AlleleCall/AlleleCall.py", line 2694, in main
    loci_modes = loci_mode_file(schema_loci_fullpath, loci_modes_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/chewbacca_cgmlst/lib/python3.11/site-packages/CHEWBBACA/AlleleCall/AlleleCall.py", line 71, in loci_mode_file
    loci_modes[locus_id] = [sm.determine_mode(allele_sizes)[0], allele_sizes]
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/chewbacca_cgmlst/lib/python3.11/site-packages/CHEWBBACA/utils/sequence_manipulation.py", line 266, in determine_mode
    modes = [most_common[0][0]]
             ~~~~~~~~~~~^^^
IndexError: list index out of range
```
The solutions suggested in https://github.com/B-UMMI/chewBBACA/issues/154#issuecomment-1375992870 did not seem to work.
Please advise on possible workarounds.
Thank you!

**Comment by rfm-targa** [comment]
Hello @omegatro!

I have adapted the _S. enterica_ schema from Ridom and could not reproduce the error while performing allele calling with the genome assembly you shared. The schema I downloaded from Ridom contained an empty FASTA file. It contains 3,002 files, but chewBBACA only detects 3,001 as valid FASTA files. The empty file is excluded from the subsequent steps because it's empty. I have also noticed that you are passing the same directory as input and output to the PrepExternalSchema module. I suggest you readapt the schema and provide a different output path, preferably a path to a new directory that chewBBACA can create to store the adapted schema. I think the issue you're encountering is related to the input and output directories being the same. chewBBACA does not delete the empty FASTA file, meaning it stays in the directory where chewBBACA stores the adapted schema files. The empty FASTA file might be causing the error because chewBBACA has to compute the allele length mode for all loci and cannot do it for the empty FASTA file, failing unexpectedly.
Let me know if my suggestions help.

Best regards,

Rafael

**Comment by omegatro** [comment]
Hello!

Thank you, the suggestion worked perfectly. 
AlleleCall worked as expected if empty fasta file for STMMW_45061 locus was removed prior to adapting the schema.
