### ISSUE TITLE
File not found because of wrong path AlleleCall

### ISSUE THREAD

**Issue by mlarjim** [B-UMMI/chewBBACA#187]
Dear chewBBACA team,

I got this error when executing AlleleCall (inferring alleles mode):

```
Traceback (most recent call last):
  File "/-/chew3/bin/chewBBACA.py", line 10, in <module>
    sys.exit(main())
  File "/-/chew3/lib/python3.10/site-packages/CHEWBBACA/chewBBACA.py", line 1526, in main
    functions_info[process][1]()
  File "/-/chew3/lib/python3.10/site-packages/CHEWBBACA/utils/process_datetime.py", line 143, in wrapper
    func(*args, **kwargs)
  File "/-/chew3/lib/python3.10/site-packages/CHEWBBACA/chewBBACA.py", line 455, in allele_call
    AlleleCall.main(genome_list, loci_list, args.schema_directory, args.output_directory,
  File "/-/chew3/lib/python3.10/site-packages/CHEWBBACA/AlleleCall/AlleleCall.py", line 2448, in main
    fo.pickle_dumper(current_dna_table, latest_dna_table)
  File "/-/chew3/lib/python3.10/site-packages/CHEWBBACA/utils/file_operations.py", line 266, in pickle_dumper
    with open(output_file, 'wb') as poutfile:
FileNotFoundError: [Errno 2] No such file or directory: '/-/databases/chewbbaca/sent_enterobase_cgmlst/pre_computed/D/N/A/t/a/b/l/e/1/0'
```

File "pre_computed/D/N/A/t/a/b/l/e/1/0" does not exist, but "pre_computed/DNAtable10" exists.

Everything was executed correctly but the output files were not created. 
I was able to by-pass this problem adding brackets to the child_targets of fo.join_paths function in AllelCall.py line2442:

`latest_dna_table = fo.join_paths(pre_computed_dir, ['DNAtable{0}'.format(new_index)])`

But maybe this is not the best solution because other paths may be affected and I do not know what DNAtable files are for. Could you please check it?

(The schema used for allele calling was created from enterobase alleles of Salmonella enterica using chewBBACA PrepExternalSchema function, default values, training file from chewie wgMLST)

**Comment by rfm-targa** [comment]
Hello @mlarjim,

What is the version of chewBBACA that you are using? I think this was an issue in an older version. The latest versions include the square brackets. I suggest you update or create a new environment with chewBBACA v3.2.0. You can find that version in Conda and PyPI.
Please let me know if updating/reinstalling solved the issue.

Best regards,

Rafael

**Comment by mlarjim** [comment]
Hi Rafael,
Sorry, actually using v3.0.0. Updating chewbbaca solves the problem, thank you so much!

**Comment by rfm-targa** [comment]
Hello @mlarjim,

It is good to know that updating solved the issue.
I will close this issue, but let me know if there is anything else.

Rafael
