### ISSUE TITLE
AlleleCall - Error in translate_fasta and protein_alignment

### ISSUE THREAD

**Issue by jdaeth274** [B-UMMI/chewBBACA#199]
Hi chewBBACA team

I'm running into an issue when using the `AlleleCall` option with `chewBBACA v3.3.4`. I have 347 bordetella assemblies and I'm using an external scheme that I have already run `PrepExternalSchema` successfully on. It seems to fail with the `translate_fasta` function at the Protein clustering stage. Produces quite a few python errors, but then doesn't exit till the `Aligning of cluster representatives against clustered proteins` stage with a module import error. 

The command, conda environment and truncated STDOUT and STDERR are printed here for reference. 

Any help would be greatly appreciated! 

## Command
```
chewBBACA.py AlleleCall -i ./bordy_trimmed_347_assemblies.txt \
-g ./chewbbaca_schema  \
-o pertussis_chewbbaca_347 \
--cpu 6
```

## Conda environment
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
archspec                  0.2.3              pyhd8ed1ab_0    conda-forge
biopython                 1.83             py39hd1e30aa_0    conda-forge
blast                     2.15.0          pl5321h6f7f691_1    bioconda
brotli-python             1.1.0            py39h3d6467e_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.28.1               hd590300_0    conda-forge
ca-certificates           2024.6.2             hbcca054_0    conda-forge
certifi                   2024.6.2           pyhd8ed1ab_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
chewbbaca                 3.3.4              pyhdfd78af_0    bioconda
curl                      8.7.1                hca28451_0    conda-forge
entrez-direct             21.6                 he881be0_0    bioconda
fasttree                  2.1.11               h031d066_3    bioconda
gawk                      5.3.0                ha916aea_0    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gmp                       6.3.0                h59595ed_1    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
importlib-metadata        7.1.0              pyha770c72_0    conda-forge
isodate                   0.6.1              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libblas                   3.9.0           21_linux64_openblas    conda-forge
libcblas                  3.9.0           21_linux64_openblas    conda-forge
libcurl                   8.7.1                hca28451_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_5    conda-forge
libgfortran-ng            13.2.0               h69a702a_5    conda-forge
libgfortran5              13.2.0               ha4646dd_5    conda-forge
libgomp                   13.2.0               h807b86a_5    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libidn2                   2.3.7                hd590300_0    conda-forge
liblapack                 3.9.0           21_linux64_openblas    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.26          pthreads_h413a1c8_0    conda-forge
libsqlite                 3.45.2               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_5    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.9.14               h22db469_4    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
mafft                     7.525                h031d066_1    bioconda
mpfr                      4.2.1                h9458935_0    conda-forge
ncbi-vdb                  3.1.0                hdbdd923_0    bioconda
ncurses                   6.4.20240210         h59595ed_0    conda-forge
numpy                     1.26.4           py39h474f0d3_0    conda-forge
openssl                   3.3.1                h4ab18f5_0    conda-forge
ossuuid                   1.6.2             hf484d3e_1000    conda-forge
packaging                 24.0               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2            py39hfc16268_1    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
perl                      5.32.1          7_hd590300_perl5    conda-forge
perl-alien-build          2.48            pl5321hec16e2b_0    bioconda
perl-alien-libxml2        0.17            pl5321hec16e2b_0    bioconda
perl-archive-tar          2.40            pl5321hdfd78af_0    bioconda
perl-business-isbn        3.007           pl5321hdfd78af_0    bioconda
perl-business-isbn-data   20210112.006    pl5321hdfd78af_0    bioconda
perl-capture-tiny         0.48            pl5321hdfd78af_2    bioconda
perl-carp                 1.38            pl5321hdfd78af_4    bioconda
perl-common-sense         3.75            pl5321hdfd78af_0    bioconda
perl-compress-raw-bzip2   2.201           pl5321h87f3376_1    bioconda
perl-compress-raw-zlib    2.105           pl5321h87f3376_0    bioconda
perl-constant             1.33            pl5321hdfd78af_2    bioconda
perl-data-dumper          2.183           pl5321hec16e2b_1    bioconda
perl-encode               3.19            pl5321hec16e2b_1    bioconda
perl-exporter             5.72            pl5321hdfd78af_2    bioconda
perl-exporter-tiny        1.002002        pl5321hdfd78af_0    bioconda
perl-extutils-makemaker   7.70            pl5321hd8ed1ab_0    conda-forge
perl-ffi-checklib         0.28            pl5321hdfd78af_0    bioconda
perl-file-chdir           0.1010          pl5321hdfd78af_3    bioconda
perl-file-path            2.18            pl5321hd8ed1ab_0    conda-forge
perl-file-temp            0.2304          pl5321hd8ed1ab_0    conda-forge
perl-file-which           1.24            pl5321hd8ed1ab_0    conda-forge
perl-importer             0.026           pl5321hdfd78af_0    bioconda
perl-io-compress          2.201           pl5321hdbdd923_2    bioconda
perl-io-zlib              1.14            pl5321hdfd78af_0    bioconda
perl-json                 4.10            pl5321hdfd78af_0    bioconda
perl-json-xs              2.34            pl5321h4ac6f70_6    bioconda
perl-list-moreutils       0.430           pl5321hdfd78af_0    bioconda
perl-list-moreutils-xs    0.430           pl5321h031d066_2    bioconda
perl-mime-base64          3.16            pl5321hec16e2b_2    bioconda
perl-parent               0.236           pl5321hdfd78af_2    bioconda
perl-path-tiny            0.122           pl5321hdfd78af_0    bioconda
perl-pathtools            3.75            pl5321hec16e2b_3    bioconda
perl-scalar-list-utils    1.62            pl5321hec16e2b_1    bioconda
perl-scope-guard          0.21            pl5321hdfd78af_3    bioconda
perl-sub-info             0.002           pl5321hdfd78af_1    bioconda
perl-term-table           0.016           pl5321hdfd78af_0    bioconda
perl-test2-suite          0.000145        pl5321hdfd78af_0    bioconda
perl-types-serialiser     1.01            pl5321hdfd78af_0    bioconda
perl-uri                  5.12            pl5321hdfd78af_0    bioconda
perl-xml-libxml           2.0207          pl5321h661654b_0    bioconda
perl-xml-namespacesupport 1.12            pl5321hdfd78af_1    bioconda
perl-xml-sax              1.02            pl5321hdfd78af_1    bioconda
perl-xml-sax-base         1.09            pl5321hdfd78af_1    bioconda
pip                       24.0               pyhd8ed1ab_0    conda-forge
plotly                    5.19.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pyrodigal                 3.4.1            py39hff71179_1    bioconda
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.9.19          h0755675_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      4_cp39    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
rdflib                    7.0.0              pyhd8ed1ab_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
scipy                     1.13.1           py39haf93ffa_0    conda-forge
setuptools                69.2.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sparqlwrapper             2.0.0              pyha770c72_0    conda-forge
tenacity                  8.2.3              pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
urllib3                   2.2.1              pyhd8ed1ab_0    conda-forge
wget                      1.21.4               hda4d442_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```
## STDOUT and STDERR snapshot
```
chewBBACA version: 3.3.4
Authors: Rafael Mamede, Pedro Cerqueira, Mickael Silva, João Carriço, Mário Ramirez
Github: https://github.com/B-UMMI/chewBBACA
Documentation: https://chewbbaca.readthedocs.io/en/latest/index.html
Contacts: imm-bioinfo@medicina.ulisboa.pt

==========================
  chewBBACA - AlleleCall
==========================
Started at: 2024-06-11T10:01:02

Output directory exists. Will store results in pertussis_chewbbaca_347/results_20240611T100102

 Configuration values 
======================
Minimum sequence length: 0
Size threshold: 0.2
Translation table: 11
BLAST Score Ratio: 0.6
Word size: 5
Window size: 5
Clustering similarity: 0.2
Prodigal training file: None
CPU cores: 6
BLAST path: /home/phe.gov.uk/joshua.daeth/miniforge3/envs/chewbbacca_env/bin
CDS input: False
Prodigal mode: single
Mode: 4
Number of inputs: 347
Number of loci: 1414
Intermediate files will be stored in pertussis_chewbbaca_347/results_20240611T100102/temp

 Pre-computed data 
===================
Loci allele size mode values stored in /home/phe.gov.uk/joshua.daeth/Nextcloud/Documents/bordetella/pasteur_genus_cgMLST/chewbbaca_schema/loci_modes
Hash tables stored in /home/phe.gov.uk/joshua.daeth/Nextcloud/Documents/bordetella/pasteur_genus_cgMLST/chewbbaca_schema/pre_computed

 CDS prediction 
================
Predicting CDSs for 347 inputs...
 [====================] 100%
Extracted a total of 1347156 CDSs from 347 inputs.

 CDS deduplication 
===================
Identifying distinct CDSs...
Identified 82664 distinct CDSs.

 CDS exact matching 
====================
Searching for CDS exact matches...
Found 426907 exact matches (20831 distinct schema alleles).
Unclassified CDSs: 61833

 CDS translation 
=================
Translating 61833 CDSs...
 [====================] 100%
0 CDSs could not be translated.
Unclassified CDSs: 61833

 Protein deduplication 
=======================
Identifying distinct proteins...
Identified 39835 distinct proteins.

 Protein exact matching 
========================
Searching for Protein exact matches...
Found 144 exact matches (230 distinct CDSs, 553 total CDSs).
Unclassified proteins: 39691

 Protein clustering 
====================
Translating schema representative alleles...

Error on translate_fasta:
Traceback (most recent call last):
  File "/home/phe.gov.uk/joshua.daeth/miniforge3/envs/chewbbacca_env/lib/python3.9/site-packages/CHEWBBACA/utils/multiprocessing_operations.py", line 42, in function_helper
    results = input_args[-1](*input_args[0:-1])
  File "/home/phe.gov.uk/joshua.daeth/miniforge3/envs/chewbbacca_env/lib/python3.9/site-packages/CHEWBBACA/utils/fasta_operations.py", line 492, in translate_fasta
    translated_records = [[rec.id,
  File "/home/phe.gov.uk/joshua.daeth/miniforge3/envs/chewbbacca_env/lib/python3.9/site-packages/CHEWBBACA/utils/fasta_operations.py", line 492, in <listcomp>
    translated_records = [[rec.id,
  File "/home/phe.gov.uk/joshua.daeth/miniforge3/envs/chewbbacca_env/lib/python3.9/site-packages/Bio/SeqIO/Interfaces.py", line 85, in __next__
    return next(self.records)
  File "/home/phe.gov.uk/joshua.daeth/miniforge3/envs/chewbbacca_env/lib/python3.9/site-packages/Bio/SeqIO/FastaIO.py", line 199, in iterate
    for title, sequence in SimpleFastaParser(handle):
  File "/home/phe.gov.uk/joshua.daeth/miniforge3/envs/chewbbacca_env/lib/python3.9/site-packages/Bio/SeqIO/FastaIO.py", line 52, in SimpleFastaParser
    for line in handle:
  File "/home/phe.gov.uk/joshua.daeth/miniforge3/envs/chewbbacca_env/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

--- Error in translate_fasta repeated 1,414 times 

Representative BLASTp self-scores stored in /home/phe.gov.uk/joshua.daeth/Nextcloud/Documents/bordetella/pasteur_genus_cgMLST/chewbbaca_schema/short/self_scores
Creating minimizer index for representative alleles...
Created index with 158854 distinct minimizers for 1414 loci.
Clustering proteins...
 [====================] 100%
Clustered 1992 proteins into 1116 clusters.
37699 proteins were not added to any cluster.
Aligning cluster representatives against clustered proteins...
Traceback (most recent call last):
  File "/home/phe.gov.uk/joshua.daeth/miniforge3/envs/chewbbacca_env/bin/chewBBACA.py", line 10, in <module>
    sys.exit(main())
  File "/home/phe.gov.uk/joshua.daeth/miniforge3/envs/chewbbacca_env/lib/python3.9/site-packages/CHEWBBACA/chewBBACA.py", line 1643, in main
    functions_info[process][1]()
  File "/home/phe.gov.uk/joshua.daeth/miniforge3/envs/chewbbacca_env/lib/python3.9/site-packages/CHEWBBACA/utils/process_datetime.py", line 146, in wrapper
    func(*args, **kwargs)
  File "/home/phe.gov.uk/joshua.daeth/miniforge3/envs/chewbbacca_env/lib/python3.9/site-packages/CHEWBBACA/chewBBACA.py", line 525, in run_allele_call
    allele_call.main(genome_list, loci_list, args.schema_directory,
  File "/home/phe.gov.uk/joshua.daeth/miniforge3/envs/chewbbacca_env/lib/python3.9/site-packages/CHEWBBACA/AlleleCall/allele_call.py", line 2813, in main
    results = allele_calling(input_files, schema_directory,
  File "/home/phe.gov.uk/joshua.daeth/miniforge3/envs/chewbbacca_env/lib/python3.9/site-packages/CHEWBBACA/AlleleCall/allele_call.py", line 2367, in allele_calling
    blast_results, blast_results_dir = cf.blast_clusters(clusters, all_prots,
  File "/home/phe.gov.uk/joshua.daeth/miniforge3/envs/chewbbacca_env/lib/python3.9/site-packages/CHEWBBACA/utils/core_functions.py", line 762, in blast_clusters
    db_std = bw.make_blast_db(makeblastdb_path, sequences, blast_db, 'prot')
  File "/home/phe.gov.uk/joshua.daeth/miniforge3/envs/chewbbacca_env/lib/python3.9/site-packages/CHEWBBACA/utils/blast_wrapper.py", line 62, in make_blast_db
    sys.exit(f'Could not create BLAST database for {input_fasta}\n'
NameError: name 'sys' is not defined
```

**Comment by rfm-targa** [comment]
Hello @jdaeth274,

Thank you for sharing the details. Indeed, it seems there is an issue in the step that translates the schema representative alleles. The FASTA files with the representative alleles should be in the `./chewbbaca_schema/short` directory. I advise verifying that that folder includes one FASTA file per locus in the schema (the files terminate in `short.fasta`). The folder should only contain the FASTA files and a file named `self_scores`. Any additional files might lead to errors. The error might also arise if the FASTA files are not well formatted (if it fails to translate the alleles in all the files, verifying/validating a few files might help identify the issue).
If it's not an issue, you can also send us the schema so that we can verify everything and fix any bugs in chewBBACA.

Best regards,

Rafael

**Comment by jdaeth274** [comment]
Hi @rfm-targa 

Thanks for getting back to me on this! I had a look back into the schema, I think I'd actually created this with a slightly older version of `chewBBACA` so re-ran the `PrepExternalSchema` command. I also had some long fasta headers in my assembly files - output from `shovill` with > 50 characters, so I shortened these and the actual filenames to < 50 characters. Combined this solved the problem.  

I can also send over the old schema directory if you'd like.

Cheers
Josh

**Comment by rfm-targa** [comment]
Hi @jdaeth274,

It's good to know that you got everything working. Older schemas included files that are no longer used or supported. We will add a check to improve legacy schema detection. I will install an older version to test that, so you don't have to send us the schema directory. Thank you.
Closing this issue. Let us know if anything else comes up.

Best regards,

Rafael
