### ISSUE TITLE
AlleleCallEvaluator Issue - KeyError

### ISSUE THREAD

**Issue by arshdeep1k** [B-UMMI/chewBBACA#205]
Hello, I have been trying to use chewBBACA with Salmonella enterica scheme from chewie-NS. 
I started with a small dataset of 10 sequences, have been running into the Key error when trying to use AlleleCallEvaluator.

At first I thought it could be a sample issue, I removed the sample it was referencing in the KeyError, and then re-ran AlleleCall followed by Evaluator, and now the same error is coming up but referencing a new sample.

Below is the command I ran and the error output. 

`
$ chewBBACA.py AlleleCallEvaluator -i 20240819_test_results2/ -g /phe/tools/chewbbaca/Senterica/prep_schema -o 20240819_test_results2/alleleEvaluate --cpu 8
chewBBACA version: 3.3.6
Authors: Rafael Mamede, Pedro Cerqueira, Mickael Silva, João Carriço, Mário Ramirez
Github: https://github.com/B-UMMI/chewBBACA
Documentation: https://chewbbaca.readthedocs.io/en/latest/index.html
Contacts: imm-bioinfo@medicina.ulisboa.pt

===================================
  chewBBACA - AlleleCallEvaluator
===================================
Started at: 2024-08-19T15:52:16

Number of samples: 9
Number of loci: 8558
Computing sample statistics...Traceback (most recent call last):
  File "/phe/tools/miniconda3/envs/chewbbaca/bin/chewBBACA.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/phe/tools/miniconda3/envs/chewbbaca/lib/python3.11/site-packages/CHEWBBACA/chewBBACA.py", line 1474, in main
    functions_info[process][1]()
  File "/phe/tools/miniconda3/envs/chewbbaca/lib/python3.11/site-packages/CHEWBBACA/utils/process_datetime.py", line 146, in wrapper
    func(*args, **kwargs)
  File "/phe/tools/miniconda3/envs/chewbbaca/lib/python3.11/site-packages/CHEWBBACA/chewBBACA.py", line 698, in run_evaluate_calls
    evaluate_calls.main(**vars(args))
  File "/phe/tools/miniconda3/envs/chewbbaca/lib/python3.11/site-packages/CHEWBBACA/AlleleCallEvaluator/evaluate_calls.py", line 285, in main
    sample_stats = compute_sample_stats(sample_ids, total_loci,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/phe/tools/miniconda3/envs/chewbbaca/lib/python3.11/site-packages/CHEWBBACA/AlleleCallEvaluator/evaluate_calls.py", line 81, in compute_sample_stats
    if current_line[1] not in sample_stats[current_line[0]][2]:
                              ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: '2417314507'
`
If you could please look into it and help troubleshoot, that"ll be great. Thank you

**Comment by ramirma** [comment]
Thank you for your interest in chewBBACA @arshdeep1k. Can you update to the latest release (3.3.10) and see if you can reproduce the error? We noted a number of problems when the locus/genome names were composed of digits that we solved in more recent releases.

**Comment by arshdeep1k** [comment]
Hi @ramirma, Thank you for the suggestion, the latest version seems to have resolved the issues I was having.
