### ISSUE TITLE
numpy version issue

### ISSUE THREAD

**Issue by tiagofilipe12** [B-UMMI/chewBBACA#3]
while using numpy version 1.13.3, chewBBACA.py retrieved:

```
Traceback (most recent call last):
  File "/usr/bin/chewBBACA.py", line 7, in <module>
    from CHEWBBACA.chewBBACA import main
  File "/usr/lib/python3.6/site-packages/CHEWBBACA/chewBBACA.py", line 18, in <module>
    from CHEWBBACA.allelecall import BBACA
  File "/usr/lib/python3.6/site-packages/CHEWBBACA/allelecall/BBACA.py", line 19, in <module>
    from CHEWBBACA.utils import ParalogPrunning
  File "/usr/lib/python3.6/site-packages/CHEWBBACA/utils/ParalogPrunning.py", line 4, in <module>
    from numpy import array
ImportError: cannot import name 'array'
```

I tested using numpy-1.14-0 and it all went well, maybe you can change it to `numpy>=1.14.0` in requirementes.txt

**Comment by mickaelsilva** [comment]
Hmm that's a strange behavior, thanks for the heads up tiago.

Requirements corrected.
