### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by stan-iakhno** [B-UMMI/chewBBACA#59]
Hello there! I run int a problem when installing with pip3:
```pip3 install chewbbaca
Collecting chewbbaca
  Using cached https://files.pythonhosted.org/packages/b1/79/a5422033716f970b3d4afaaafd9f8112da6604721a1819f8c7c6e87c6948/chewBBACA-2.1.0-py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests>=2.2.1 in /usr/lib/python3/dist-packages (from chewbbaca)
Collecting scipy>=0.13.3 (from chewbbaca)
  Using cached https://files.pythonhosted.org/packages/c1/60/8cbf00c0deb50a971e6e3a015fb32513960a92867df979870a454481817c/scipy-1.4.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting biopython>=1.70 (from chewbbaca)
  Using cached https://files.pythonhosted.org/packages/59/8f/454d961e821d5f600eb59885dc32aa39e3f226357f5d18a839d7ae088722/biopython-1.76-cp35-cp35m-manylinux1_x86_64.whl
Collecting numpy>=1.14.0 (from chewbbaca)
  Using cached https://files.pythonhosted.org/packages/45/25/48e4ea892e93348d48a3a0d23ad94b176d6ab66084efcd881c78771d4abf/numpy-1.18.3-cp35-cp35m-manylinux1_x86_64.whl
Collecting pandas>=0.22.0 (from chewbbaca)
  Using cached https://files.pythonhosted.org/packages/2f/79/f236ab1cfde94bac03d7b58f3f2ab0b1cc71d6a8bda3b25ce370a9fe4ab1/pandas-1.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-tl3xfffe/pandas/setup.py", line 42
        f"numpy >= {min_numpy_ver}",
                                  ^
    SyntaxError: invalid syntax
```

Could you kindly suggest a fix for this?

Regards. Stan

**Comment by mickaelsilva** [comment]
Hello @stan-iakhno, can you provide us the python version and OS are you using so we can try to replicate the error?

cheers

**Comment by stan-iakhno** [comment]
Thanks for your prompt reply @mickaelsilva ! Here are the specs:
```
$ python3 --version
Python 3.7.7
```

OS:
```
stanislav-thinkpad-p71
    description: Computer
    width: 64 bits
    capabilities: vsyscall32
  *-core
       description: Motherboard
       physical id: 0
     *-memory
          description: System memory
          physical id: 0
          size: 31GiB
     *-cpu
          product: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
          vendor: Intel Corp.
          physical id: 1
          bus info: cpu@0
          size: 3181MHz
          capacity: 3900MHz
          width: 64 bits
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp x86-64 constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d cpufreq
     *-pci
          description: Host bridge
          product: Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers
          vendor: Intel Corporation
          physical id: 100
          bus info: pci@0000:00:00.0
          version: 05
          width: 32 bits
          clock: 33MHz
        *-pci:0
             description: PCI bridge
             product: Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller (x16)
             vendor: Intel Corporation
             physical id: 1
             bus info: pci@0000:00:01.0
             version: 05
             width: 32 bits
             clock: 33MHz
             capabilities: pci normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:16 ioport:d000(size=4096) memory:e3000000-e40fffff ioport:a0000000(size=301989888)
           *-display
                description: 3D controller
                product: GP104GLM [Quadro P3000 Mobile]
                vendor: NVIDIA Corporation
                physical id: 0
                bus info: pci@0000:01:00.0
                version: a1
                width: 64 bits
                clock: 33MHz
                capabilities: bus_master cap_list rom
                configuration: driver=nouveau latency=0
                resources: irq:126 memory:e3000000-e3ffffff memory:a0000000-afffffff memory:b0000000-b1ffffff ioport:d000(size=128) memory:e4000000-e407ffff
        *-display
             description: VGA compatible controller
             product: Intel Corporation
             vendor: Intel Corporation
             physical id: 2
             bus info: pci@0000:00:02.0
             version: 04
             width: 64 bits
             clock: 33MHz
             capabilities: vga_controller bus_master cap_list rom
             configuration: driver=i915 latency=0
             resources: iomemory:2f0-2ef iomemory:2f0-2ef irq:141 memory:2ffa000000-2ffaffffff memory:2fa0000000-2fafffffff ioport:e000(size=64) memory:c0000-dffff
        *-generic:0 UNCLAIMED
             description: System peripheral
             product: Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th Gen Core Processor Gaussian Mixture Model
             vendor: Intel Corporation
             physical id: 8
             bus info: pci@0000:00:08.0
             version: 00
             width: 64 bits
             clock: 33MHz
             capabilities: cap_list
             configuration: latency=0
             resources: iomemory:2f0-2ef memory:2ffb018000-2ffb018fff
        *-usb
             description: USB controller
             product: 100 Series/C230 Series Chipset Family USB 3.0 xHCI Controller
             vendor: Intel Corporation
             physical id: 14
             bus info: pci@0000:00:14.0
             version: 31
             width: 64 bits
             clock: 33MHz
             capabilities: xhci bus_master cap_list
             configuration: driver=xhci_hcd latency=0
             resources: irq:120 memory:e5920000-e592ffff
        *-generic:1
             description: Signal processing controller
             product: 100 Series/C230 Series Chipset Family Thermal Subsystem
             vendor: Intel Corporation
             physical id: 14.2
             bus info: pci@0000:00:14.2
             version: 31
             width: 64 bits
             clock: 33MHz
             capabilities: cap_list
             configuration: driver=intel_pch_thermal latency=0
             resources: iomemory:2f0-2ef irq:19 memory:2ffb017000-2ffb017fff
        *-generic:2
             description: Signal processing controller
             product: 100 Series/C230 Series Chipset Family Serial IO I2C Controller #0
             vendor: Intel Corporation
             physical id: 15
             bus info: pci@0000:00:15.0
             version: 31
             width: 64 bits
             clock: 33MHz
             capabilities: bus_master cap_list
             configuration: driver=intel-lpss latency=0
             resources: iomemory:2f0-2ef irq:16 memory:2ffb016000-2ffb016fff
        *-communication:0
             description: Communication controller
             product: 100 Series/C230 Series Chipset Family MEI Controller #1
             vendor: Intel Corporation
             physical id: 16
             bus info: pci@0000:00:16.0
             version: 31
             width: 64 bits
             clock: 33MHz
             capabilities: bus_master cap_list
             configuration: driver=mei_me latency=0
             resources: iomemory:2f0-2ef irq:142 memory:2ffb015000-2ffb015fff
        *-communication:1
             description: Serial controller
             product: 100 Series/C230 Series Chipset Family KT Redirection
             vendor: Intel Corporation
             physical id: 16.3
             bus info: pci@0000:00:16.3
             version: 31
             width: 32 bits
             clock: 66MHz
             capabilities: 16550 cap_list
             configuration: driver=serial latency=0
             resources: irq:19 ioport:e088(size=8) memory:e5938000-e5938fff
        *-storage
             description: SATA controller
             product: Q170/Q150/B150/H170/H110/Z170/CM236 Chipset SATA Controller [AHCI Mode]
             vendor: Intel Corporation
             physical id: 17
             bus info: pci@0000:00:17.0
             version: 31
             width: 32 bits
             clock: 66MHz
             capabilities: storage ahci_1.0 bus_master cap_list
             configuration: driver=ahci latency=0
             resources: irq:121 memory:e5934000-e5935fff memory:e5937000-e59370ff ioport:e080(size=8) ioport:e090(size=4) ioport:e060(size=32) memory:e5936000-e59367ff
        *-pci:1
             description: PCI bridge
             product: 100 Series/C230 Series Chipset Family PCI Express Root Port #17
             vendor: Intel Corporation
             physical id: 1b
             bus info: pci@0000:00:1b.0
             version: f1
             width: 32 bits
             clock: 33MHz
             capabilities: pci normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:16 memory:e5800000-e58fffff
           *-storage
                description: Non-Volatile memory controller
                product: NVMe SSD Controller SM981/PM981
                vendor: Samsung Electronics Co Ltd
                physical id: 0
                bus info: pci@0000:02:00.0
                version: 00
                width: 64 bits
                clock: 33MHz
                capabilities: storage nvm_express bus_master cap_list
                configuration: driver=nvme latency=0
                resources: irq:16 memory:e5800000-e5803fff
        *-pci:2
             description: PCI bridge
             product: 100 Series/C230 Series Chipset Family PCI Express Root Port #1
             vendor: Intel Corporation
             physical id: 1c
             bus info: pci@0000:00:1c.0
             version: f1
             width: 32 bits
             clock: 33MHz
             capabilities: pci normal_decode cap_list
             configuration: driver=pcieport
             resources: irq:16 ioport:c000(size=4096) memory:e4e00000-e57fffff ioport:e4100000(size=10485760)
        *-pci:3
             description: PCI bridge
             product: 100 Series/C230 Series Chipset Family PCI Express Root Port #3
             vendor: Intel Corporation
             physical id: 1c.2
             bus info: pci@0000:00:1c.2
             version: f1
             width: 32 bits
             clock: 33MHz
             capabilities: pci normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:18 memory:e4d00000-e4dfffff
           *-network
                description: Wireless interface
                product: Wireless 8265 / 8275
                vendor: Intel Corporation
                physical id: 0
                bus info: pci@0000:04:00.0
                logical name: wlp4s0
                version: 78
                serial: ac:ed:5c:d2:b9:d2
                width: 64 bits
                clock: 33MHz
                capabilities: bus_master cap_list ethernet physical wireless
                configuration: broadcast=yes driver=iwlwifi driverversion=4.15.0-50-generic firmware=34.0.1 ip=192.168.0.6 latency=0 link=yes multicast=yes wireless=IEEE 802.11
                resources: irq:143 memory:e4d00000-e4d01fff
        *-pci:4
             description: PCI bridge
             product: 100 Series/C230 Series Chipset Family PCI Express Root Port #5
             vendor: Intel Corporation
             physical id: 1c.4
             bus info: pci@0000:00:1c.4
             version: f1
             width: 32 bits
             clock: 33MHz
             capabilities: pci normal_decode cap_list
             configuration: driver=pcieport
             resources: irq:16 ioport:2000(size=4096) memory:b4000000-e20fffff ioport:2fb0000000(size=1241513984)
        *-pci:5
             description: PCI bridge
             product: 100 Series/C230 Series Chipset Family PCI Express Root Port #9
             vendor: Intel Corporation
             physical id: 1d
             bus info: pci@0000:00:1d.0
             version: f1
             width: 32 bits
             clock: 33MHz
             capabilities: pci normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:16 memory:e4c00000-e4cfffff
           *-storage
                description: Non-Volatile memory controller
                product: NVMe SSD Controller SM961/PM961
                vendor: Samsung Electronics Co Ltd
                physical id: 0
                bus info: pci@0000:70:00.0
                version: 00
                width: 64 bits
                clock: 33MHz
                capabilities: storage nvm_express bus_master cap_list
                configuration: driver=nvme latency=0
                resources: irq:16 memory:e4c00000-e4c03fff
        *-pci:6
             description: PCI bridge
             product: 100 Series/C230 Series Chipset Family PCI Express Root Port #13
             vendor: Intel Corporation
             physical id: 1d.4
             bus info: pci@0000:00:1d.4
             version: f1
             width: 32 bits
             clock: 33MHz
             capabilities: pci normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:16 memory:e4b00000-e4bfffff
           *-generic
                description: Unassigned class
                product: RTS525A PCI Express Card Reader
                vendor: Realtek Semiconductor Co., Ltd.
                physical id: 0
                bus info: pci@0000:71:00.0
                version: 01
                width: 32 bits
                clock: 33MHz
                capabilities: bus_master cap_list
                configuration: driver=rtsx_pci latency=0
                resources: irq:122 memory:e4b00000-e4b00fff
        *-isa
             description: ISA bridge
             product: CM238 Chipset LPC/eSPI Controller
             vendor: Intel Corporation
             physical id: 1f
             bus info: pci@0000:00:1f.0
             version: 31
             width: 32 bits
             clock: 33MHz
             capabilities: isa bus_master
             configuration: latency=0
        *-memory UNCLAIMED
             description: Memory controller
             product: 100 Series/C230 Series Chipset Family Power Management Controller
             vendor: Intel Corporation
             physical id: 1f.2
             bus info: pci@0000:00:1f.2
             version: 31
             width: 32 bits
             clock: 33MHz (30.3ns)
             configuration: latency=0
             resources: memory:e5930000-e5933fff
        *-multimedia
             description: Audio device
             product: CM238 HD Audio Controller
             vendor: Intel Corporation
             physical id: 1f.3
             bus info: pci@0000:00:1f.3
             version: 31
             width: 64 bits
             clock: 33MHz
             capabilities: bus_master cap_list
             configuration: driver=snd_hda_intel latency=64
             resources: iomemory:2f0-2ef iomemory:2f0-2ef irq:144 memory:2ffb010000-2ffb013fff memory:2ffb000000-2ffb00ffff
        *-serial UNCLAIMED
             description: SMBus
             product: 100 Series/C230 Series Chipset Family SMBus
             vendor: Intel Corporation
             physical id: 1f.4
             bus info: pci@0000:00:1f.4
             version: 31
             width: 64 bits
             clock: 33MHz
             configuration: latency=0
             resources: iomemory:2f0-2ef memory:2ffb014000-2ffb0140ff ioport:efa0(size=32)
        *-network
             description: Ethernet interface
             product: Ethernet Connection (5) I219-LM
             vendor: Intel Corporation
             physical id: 1f.6
             bus info: pci@0000:00:1f.6
             logical name: enp0s31f6
             version: 31
             serial: 54:e1:ad:52:86:c3
             capacity: 1Gbit/s
             width: 32 bits
             clock: 33MHz
             capabilities: bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
             configuration: autonegotiation=on broadcast=yes driver=e1000e driverversion=3.2.6-k firmware=0.1-3 latency=0 link=no multicast=yes port=twisted pair
             resources: irq:125 memory:e5900000-e591ffff
     *-scsi
          physical id: 2
          logical name: scsi4
          capabilities: emulated
        *-cdrom
             description: DVD-RAM writer
             product: DVDRAM GUD0N
             vendor: HL-DT-ST
             physical id: 0.0.0
             bus info: scsi@4:0.0.0
             logical name: /dev/cdrom
             logical name: /dev/cdrw
             logical name: /dev/dvd
             logical name: /dev/dvdrw
             logical name: /dev/sr0
             version: LAE1
             capabilities: removable audio cd-r cd-rw dvd dvd-r dvd-ram
             configuration: ansiversion=5 status=nodisc
```

**Comment by mickaelsilva** [comment]
@stan-iakhno ok python 3.7.7, about the OS I was only asking if its windows, linux or mac and which distro. That info you just posted is way too specific and doesn't seem to me that you should post it online for your own security.

cheers

**Comment by stan-iakhno** [comment]
@mickaelsilva , thanks for the tip. Yes, it is linux

**Comment by rfm-targa** [comment]
@stan-iakhno we are testing to identify the problem. We will let you know what it is soon.

**Comment by rfm-targa** [comment]
@stan-iakhno we could not reproduce the issue.

**Comment by rfm-targa** [comment]
@stan-iakhno we could not reproduce the issue. We suggest that you try to create a new environment that only has the Python version you want to use. If you have conda installed, you can create a new environment as follows:

`conda create --name <env_name> python=<python_version>
`

Where <env_name> is the name you want to give to your environment (e.g. test_chewie) and <python_version> is the Python version you want to install on that new environment (e.g. 3.3.7).

You should then try to install chewBBACA on that new environment. You can activate the new environment:

`conda activate test_chewie`

It is possible that when you try to install chewBBACA with pip, that pip will just use the default PYTHONPATH and you will not be able to install chewBBACA in the new environment. To avoid that, you may install pip on that new enviroment:

`conda install pip`

You'll need to find the location of the pip that you installed in the new environment and use the full path to call the pip for that environment and use it to install chewBBACA.

We've also noticed that your process was using the cache and it might be worth it to run the same command with the `--no-cache-dir` to force the download of the packages and rule out problems with chached files.

Please let us know if any of the suggestions solve your problem or if you need anything else to try this. If you cannot install by following these suggestions, it might be better to use Docker as it avoids most of the problems related with system configurations and dependencies.

**Comment by stan-iakhno** [comment]
Hello, @rfm-targa, thanks for a very nice troubleshooting walkthrough. I will let you know if I make it through. 

Cheers, Stan

**Comment by stan-iakhno** [comment]
Hi @rfm-targa @mickaelsilva , I have resolved the issue by using conda on a cluster and it all works! Thanks for your help!

Cheers, Stan
