### ISSUE TITLE
TypeError: join() argument must be str or bytes, not 'list'

### ISSUE THREAD

**Issue by garmonan** [B-UMMI/chewBBACA#99]
Hi!

I have successfully calculated the core genome at 95% on 33 complete genomes of my species of interest. Now I'm trying to perform allele calling on the remaining available genomes of the same species (236 genomes) that I also obtained from NCBI. However, I encountered an error that I don't know how to solve. 

I'm using version 2.7.0., and this is the command I used:

`chewBBACA.py AlleleCall -i ../data/partial/ -g 01_scheme_seed/ --gl 03_cgMLST_95/cgMLSTschema.txt -o 04_cgMLST_236 --cpu 14 --ptf my_training_file.trn
`

It prints the following messages and error:

```
==========================
  chewBBACA - AlleleCall
==========================
Started at: 2021-05-13T09:15:21

Traceback (most recent call last):
  File "/home/andrea/anaconda3/envs/chewbbaca/bin/chewBBACA.py", line 10, in <module>
    sys.exit(main())
  File "/home/andrea/anaconda3/envs/chewbbaca/lib/python3.7/site-packages/CHEWBBACA/chewBBACA.py", line 1414, in main
    functions_info[process][1]()
  File "/home/andrea/anaconda3/envs/chewbbaca/lib/python3.7/site-packages/CHEWBBACA/utils/process_datetime.py", line 149, in wrapper
    func(*args, **kwargs)
  File "/home/andrea/anaconda3/envs/chewbbaca/lib/python3.7/site-packages/CHEWBBACA/chewBBACA.py", line 392, in allele_call
    schema_genes = pv.check_input_type(args.genes_list, 'listGenes2Call.txt', args.schema_directory)
  File "/home/andrea/anaconda3/envs/chewbbaca/lib/python3.7/site-packages/CHEWBBACA/utils/parameters_validation.py", line 1330, in check_input_type
    for f in lines]
  File "/home/andrea/anaconda3/envs/chewbbaca/lib/python3.7/site-packages/CHEWBBACA/utils/parameters_validation.py", line 1330, in <listcomp>
    for f in lines]
  File "/home/andrea/anaconda3/envs/chewbbaca/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/andrea/anaconda3/envs/chewbbaca/lib/python3.7/genericpath.py", line 153, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'list'
```

I had no issues with the previous steps, and the only difference is the dataset used as input (which was also downloaded from NCBI).

Any ideas on what can be the problem?

Thanks a lot!!

**Comment by rfm-targa** [comment]
Greetings @garmonan,

chewBBACA's version 2.7.0 does not work properly when you pass the list of genes for the allele calling to the `--gl` parameter. Please update to chewBBACA's latest version, v2.8.4. Also make sure that the path you pass to the `-g` parameter is the complete path to the schema's directory, the directory that contains the Fasta files for all schema loci. You also do not need to pass the path to the training file to the `--ptf` parameter if you are going to use the same training file that was used to create the schema.
Let us know if updating solves the issue.

**Comment by garmonan** [comment]
Thank you, Rafael! Updating to the latest version solved the problem! I installed it recently via conda and I just thought it was the latest available one, but I'll double check next time :) 

Have a great day!

**Comment by rfm-targa** [comment]
Glad that it worked. Have a great day!
